import { ColumnType } from 'luna-orbit/OBTListGrid/IColumn';
export const insnRecordColumn = [
  {
    name: 'period',
    type: 'text',
    header: '적용기간',
    width: 150,
    alignment: 'center',
  },
  {
    name: 'basic_rate',
    type: 'group',
    header: '기본 본인부담액/률',
    width: 1056,
    columns: [
      {
        name: 'self_pay',
        type: 'group',
        header: '본인부담액/률',
        width: 352,
        columns: [
          {
            name: 'basc_drug_valu_tamt',
            type: ColumnType.number,
            header: '약값 총액',
            showZero: false,
            width: 88,
            alignment: 'center',
          },
          {
            name: 'basc_rcpy_expn_tamt',
            type: 'number',
            header: '요양급여비용총액',
            showZero: false,
            width: 88,
            alignment: 'center',
          },
          {
            name: 'basc_hsin_mnfc',
            type: 'number',
            header: '직접조제',
            showZero: false,
            width: 88,
            alignment: 'center',
          },
          {
            name: 'basc_hsin_mnfc_etc',
            type: 'number',
            header: '그 외 경우',
            showZero: false,
            width: 88,
            alignment: 'center',
          },
        ],
      },
      {
        name: 'disabled_peroson',
        type: 'group',
        header: '장애인/의료비',
        width: 352,
        columns: [
          {
            name: 'dspp_drug_valu_tamt',
            type: 'number',
            header: '약값 총액',
            showZero: false,
            width: 88,
            alignment: 'center',
          },
          {
            name: 'dspp_rcpy_expn_tamt',
            type: 'number',
            header: '요양급여비용총액',
            showZero: false,
            width: 88,
            alignment: 'center',
          },
          {
            name: 'dspp_hsin_mnfc',
            type: 'number',
            header: '직접조제',
            showZero: false,
            width: 88,
            alignment: 'center',
          },
          {
            name: 'dspp_hsin_mnfc_etc',
            type: 'number',
            header: '그 외 경우',
            showZero: false,
            width: 88,
            alignment: 'center',
          },
        ],
      },
      {
        name: 'support',
        type: 'group',
        header: '의료지원금',
        width: 352,
        columns: [
          {
            name: 'adfn_drug_valu_tamt',
            type: 'number',
            header: '약값 총액',
            showZero: false,
            width: 88,
            alignment: 'center',
          },
          {
            name: 'adfn_rcpy_expn_tamt',
            type: 'number',
            header: '요양급여비용총액',
            showZero: false,
            width: 88,
            alignment: 'center',
          },
          {
            name: 'adfn_hsin_mnfc',
            type: 'number',
            header: '직접조제',
            showZero: false,
            width: 88,
            alignment: 'center',
          },
          {
            name: 'adfn_hsin_mnfc_etc',
            type: 'number',
            header: '그 외 경우',
            showZero: false,
            width: 88,
            alignment: 'center',
          },
        ],
      },
    ],
  },
  {
    name: 'separate_rate',
    type: 'group',
    header: '별도 본인부담액/률',
    width: 560,
    columns: [
      {
        name: 'sprt_spcl_eqpm',
        type: 'number',
        header: '특수장비',
        showZero: false,
        width: 80,
        alignment: 'center',
      },
      {
        name: 'sprt_rwmt_actn',
        type: 'number',
        header: '특수재료행위료',
        showZero: false,
        width: 80,
        alignment: 'center',
      },
      {
        name: 'sprt_hptn_glyc',
        type: 'number',
        header: '고혈압/당뇨 지속진료',
        showZero: false,
        width: 80,
        alignment: 'center',
      },
      {
        name: 'sprt_fndg_exmn',
        type: 'number',
        header: '검진후 확진검사',
        showZero: false,
        width: 80,
        alignment: 'center',
      },
      {
        name: 'sprt_hpv',
        type: 'number',
        header: 'HPV/진찰상담 진찰료',
        showZero: false,
        width: 80,
        alignment: 'center',
      },
      {
        name: 'sprt_psyh_thpy',
        type: 'number',
        header: '정신요법',
        showZero: false,
        width: 80,
        alignment: 'center',
      },
      {
        name: 'sprt_tlcf_mcch',
        type: 'number',
        header: '원격협의진찰료 자문료',
        showZero: false,
        width: 80,
        alignment: 'center',
      },
    ],
  },
  {
    name: 'inty_apdy_endy',
    type: 'group',
    header: '적용/마감일',
    visible: false,
    columns: [
      {
        name: 'inty_apdy',
        type: 'text',
        header: '적용시작일',
      },
      {
        name: 'inty_endy',
        type: 'text',
        header: '적용마감일',
      },
    ],
  },
  {
    name: 'inty_hstr_cd',
    type: 'text',
    header: '이력 sequence',
    visible: false,
  },
];
